---
title: Reading Summary
author: Irene
date: '2024-08-05'
slug: reading-summary
categories:
  - Read
tags:
  - Accounting
  - Boring
  - Paper
---

To write down things while reading.


> Li, Feng, Russell Lundholm, and Michael Minnis. “A Measure of Competition Based on 10-K Filings.” Journal of Accounting Research 51, no. 2 (2013): 399–436.

- Measure of competition based on textual analysis in 10K. 
  - Competition is the cross-elasticity of demand.
  - Common competition measures like four-company ratio and HHI lack precision in measuring individual firms' operating and investing decision; they are also only based on very limited public firm samples; they also depend largely on the definition of industry. 
  -  The measure is simply the count of competition related words like “competition, competitor, competitive, compete, competing,” including those words with an “s” appended. They try to avoid words like “not,” “less,” “few,” or “limited” before the competition key words.
- Can't distinguish true competition vs managers' perception of competition.
- The mean reversion in accounting rate of return.